### ISSUE TITLE
Load only used classes

### ISSUE THREAD

**Issue by ghost** [box-project/box2#1]
It would be great if Box somehow figured out which classes were used, and only included those in the load.

The workaround for now is using an explicit file list to list all of the files.

**Comment by ghost** [comment]
After some R&D, I think the options to use a list of files, directories, finder instances, or a combination of the three will have to suffice.  A hack can be thrown together by using `get_declared_classes()`, `get_declared_interfaces()`, `get_declared_traits()`, `get_included_files()`, `get_required_files()`, and `ReflectionClass`, but the results will still not be complete.

The most reliable approach is to use the available import options.

**Comment by Seldaek** [comment]
I'd like this to be reopened. Basically what I'm looking for is a way of saying: Include all classes in `src/`, and then grab all the classes that are used/depended upon from `vendor/`. This code could be used as a starting point (it resolves extends/implements/..) https://github.com/symfony/symfony/blob/master/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php - another thing that would be needed is tokenizing everything to find all the new <class> stuff too. Obviously this won't be foolproof given the possibility of doing dynamic object creation in php, so it should be optional, but it'd still be great. Additionally one would need an option to add classes that should be included even if they're not seen as used.

This would be really neat to reduce the file size of the phar.

**Comment by ghost** [comment]
If the idea is to keep the PHAR size small, tokenizing PHP and searching for used class/interface/trait names may not be the right way to go about it.  The reason I think this is because a class you may use in your app could have a dependency to another class, which may never be used in the lifetime of your application.  e.g. You use a third party `ClassA`, which has a method that it calls in `ClassB`, but your app will never cause that to happen or ever use `ClassB`, but `ClassB` gets added to the PHAR anyway.

At my first attempt at tackling this problem, I came up with [this class](https://gist.github.com/3084682).  I then modified a copy of Box's main bin file to use that tracking class at the end:

``` php
#!/usr/bin/env php
<?php

    require __DIR__ . '/../src/vendors/autoload.php';

    $app = new KevinGH\Box\Console\Application;

    $app->setAutoExit(false);

    $status = $app->run();

    Track::toFile('classes.php', Track::getList());

    exit($status);
```

After running Box a few times with different commands, it managed to collect a decent number of dependencies that were actually used.  The problem is that it did not catch them all (the `JSONException` class was never thrown, so it was never tracked).  The reason I abandoned the idea is because it will require you to sift through the source anyway, find what is missing, and then manually adding it to the list that was generated.

If there is something I'm missing about `token_get_all`, I am all ears.  I am also open to any suggestions on modifying, or outright replacing that `Track` class that was shown earlier.  If you think this is good enough, then I will add the class as a utility class to Box, and modify Box so that it accepts the generated list when adding files to PHAR.

**Comment by Seldaek** [comment]
Ok fair enough, I guess I'll live with it for now - maybe allowing a blacklist so I can exclude files I specifically don't need would still be nice. Just to sift through the major pieces by hand.

**Comment by ghost** [comment]
I added a `blacklist` option to the list of configuration settings.

Ultimately, it will remove any file with a matching relative path.

``` json
{
    "blacklist": [
        "src/vendors/myVendor/myProduct/Skipped.php"
    ],
    "directories": [
        "src/vendors/myVendor/myProduct"
    ]
}
```

This example will gather all of the PHP scripts in `myProduct`, but will remove `Skipped.php` from the list of files that will be added.  The blacklist works for all "include" options: `file`, `directories`, and `finder`.  I know it doesn't make much sense for it to work in `file`, but they are all collected and processed at the same time.

Will this work for you?

**Comment by Seldaek** [comment]
Sure that sounds nice. Just a tiny unrelated feedback note, box-dist.json should be box.json.dist IMO to follow common patterns. Overall it looks cool and I hope I can move to using that instead of homegrown scripts eventually.

**Comment by ghost** [comment]
I decided to keep the file extension at the end in order for IDEs to properly use syntax highlighting and validation for JSON files if available.
