### ISSUE TITLE
Dependencies missing from composer.json

### ISSUE THREAD

**Issue by necrogami** [box-project/box2#101]
"herrera-io/box": "~1.6" no longer exists and prevents installing.

**Comment by stof** [comment]
This issue looks wrong to me. the package exists and it has some 1.6.x releases: https://packagist.org/packages/herrera-io/box

**Comment by kherge** [comment]
Yeah, I was able to install it recently.

Could you please provide a copy of the error message you're seeing?

**Comment by necrogami** [comment]
When i was trying to install it. Composer was telling me the package didn't exist.

**Comment by kherge** [comment]
Could you try again and copy and paste the error message?
