### ISSUE TITLE
Add current date as replacement?

### ISSUE THREAD

**Issue by micheleorselli** [box-project/box2#103]
When releasing a phar it would be nice to include a release date as composer does:

```
Composer version 1.0-dev (bc45d9185513575434021527d7756420e9f4b2cf) 2015-05-11 14:49:39
```

but as for now it doesn't seem possible. That should be relatively easy by adding a new config which behaves like `git-commit`, `git-short-commit` and so on. If you think this is an useful addition I could work on a PR

**Comment by blomnik** [comment]
+1
