### ISSUE TITLE
Merge box.json and box.json.dist

### ISSUE THREAD

**Issue by webmozart** [box-project/box2#104]
Hi! :)

At the moment, when running box with a box.json and a box.json.dist present, box completely ignores box.json.dist. I think it would be great if box would merge both, because that would allow to define the defaults in the .dist and to override specific local settings (private key) in the box.json without having to copy everything.

Cheers,
Bernhard

**Comment by llaville** [comment]
Sorry but I'm :-1: on this point of view. 
All config files that follow this pattern (E.g: phpunit) did not accept this behavior, and I consider myself a good practice. We don't have to know what parameters are taken from .dist or .json
Don't forget the KISS

**Comment by webmozart** [comment]
I don't think PHPUnit is comparable. There is no simple merging mechanism for XML files.

Since your JSON files are simple key-value files, merging is straight-forward (`array_replace()`). I think the rest is a documentation issue (e.g. noting that keys from .json are preferred over those from .json.dist - which is the case already). Actually, with the current documentation I expected this to be happening already.

**Comment by llaville** [comment]
I'm not a developer or even the lead on this project. So I gave only my point of view. This is not depends of if easy or not to do it, but just on the principle.
I'm sure that other members of this community have others point of view too. Finally it will up to Kevin to decide what to do !

**Comment by kherge** [comment]
I'm sorry for such a delayed response.

I'm torn on this issue, but I would like some input before I make a decision.

Let's say it was made possible to do what @webmozart wanted. Would adding an option to disable merging (e.g. `"merge-config": false`) address concerns @llaville had? Box would process things like so:
1. Attempt to load `box.json` first.
   - If `"merge": false` is set (which would be the default for BC), stop here and use settings as is.
   - If `"merge": true` is set, continue.
2. Attempt to load `box.json.dist`.
3. If both exist, merge settings and stop here.
4. If either exists, use the existing one.

Does that make sense? Could things be hypothetically handled better?

**Comment by webmozart** [comment]
No problem. If you feel uncomfortable about "magic" merging, you could also add a key "import" for importing another file. My use case could then simply be solved using:

``` json
{
    "import": "box.json.dist",
    "... specific keys ...": "..."
}
```

**Comment by kherge** [comment]
I like the `import` idea better.

Would it be overkill if it accepted an array of file paths, merging in the order they are provided? Kind of how Symfony's own configuration files will import from multiple sources.

**Comment by webmozart** [comment]
I think a simple path is enough for a start. Somebody can still request that feature. :)
