### ISSUE TITLE
Box add

### ISSUE THREAD

**Issue by xtrasmal** [box-project/box2#106]
How does `box add` work?

``` bash
$ box add -s "src/deploy" deploy-3feb0bf.phar

  [UnexpectedValueException]
  Cannot create phar 'src/deploy', file extension (or combination) not recognised or the directory does not exist

```

`src/deploy` is a file without extension

**Comment by kherge** [comment]
Try removing the space after `-s`.

I think that Box is treating `-s "src/deploy"` as two separate arguments.

**Comment by kherge** [comment]
Blegh, even I didn't understand my own tool correctly.

The following command works:

```
box add -s deploy-3feb0bf.phar src/deploy
```

The thing I misunderstood is that `-s` doesn't actually accept an argument. The first argument is always going to be the path to the phar. The second argument is always going to be the file you want to add.  The `-s` option (among the others also available) tells the `add` command to treat the file in the second argument as a stub.

Sorry about the confusion!
