### ISSUE TITLE
Fatal error:  Class 'phpseclib\Crypt\RSA' not found

### ISSUE THREAD

**Issue by mbrodala** [box-project/box2#118]
While executing the command `./box.phar key:extract ~/.ssh/id_rsa` I got the following error:

> PHP Fatal error:  Class 'phpseclib\Crypt\RSA' not found in phar:///.../box.phar/src/lib/KevinGH/Box/Helper/PhpSecLibHelper.php on line 22

Output of `./box --version`:

> Box version 2.6.0 build 34259e688bad430cf6e4418d4682d7650c7b90f1

**Comment by mbrodala** [comment]
Extracting the `box.phar` via `box.phar` ([we need to to deeper](http://knowyourmeme.com/memes/we-need-to-go-deeper)) shows the required file `.../src/vendors/phpseclib/phpseclib/phpseclib/Crypt/RSA.php` but that one contains a non-namespaced class `Crypt_RSA`. This hints at phpseclib 1.0 being packaged into `box.phar` instead of 2.0.

**Comment by kherge** [comment]
Whoa, yeah, that needs fixing.

Sorry for such a huge delay in response, I didn't receive any notifications from GitHub about this issue.

**Comment by mbrodala** [comment]
No worries, glad you're picking this up. :-)

**Comment by kherge** [comment]
Okay, looks like I fixed it in 2.7.0!

**Comment by mbrodala** [comment]
Thanks a lot.
