### ISSUE TITLE
Implement signed package

### ISSUE THREAD

**Issue by weierophinney** [box-project/box2#123]
Hi!

I've been using box, and recently wrote a blog post for creating signed PHAR files using Box, as well as automating creation and distribution:
- https://mwop.net/blog/2015-12-14-secure-phar-automation.html

One point that has been raised by some of my readers is that I detail creating a signed PHAR, but then use _an unsigned phar_ to create it, namely the one from box-project.

It'd be awesome if you could sign your phar files and provide a public key for verification; essentially, it would be one more level of trust in the chain. Let me know if I can be of any assistance in this!

**Comment by kherge** [comment]
What I need to know, and haven't had the opportunity to test, is if the OpenSSL extension will be required to run Box if the phar is signed.

If the answer yes, it will not be part of the primary distribution channel and we'll have to figure something out. (Just make it available on the _Releases_ page?)

If not, then the next release could be signed.

**Comment by mbrodala** [comment]
@kherge AFAIK is the OpenSSL extension required to generate and validate phar keys. But I wouldn't rule out this option. Sure, ease of use is always nice to have but security should have a higher priority here.

**Comment by kherge** [comment]
Sorry, I didn't mean to rule it out. I first thought that it would simply be available in the releases page provided by GitHub. But now that I think about it more, I think I can support it in addition to the non-signed phar.
1. You would see a separate installation instruction for the signed phar in the README with a caveat that OpenSSL is required.
2. Running `box update` using a signed phar would use a separate manifest containing signed phar updates.

I think this is something I can definitely do.

**Comment by mbrodala** [comment]
@kherge Don't forget to publish the required `<filename>.phar.pubkey` wherever possible. Preferably in locations which are reliable and unlikely to be hacked. ;-)

**Comment by mbrodala** [comment]
@kherge Any updates here?

**Comment by kherge** [comment]
I just realized (experimented with) that I can sign the phar using GPG. It allows me to build the phar as usual, as well as creating a detached signature that I can upload with each release.

I know that the original request was about embedding the signature in the phar, but would this be a good compromise? It would save me from having to create two separate builds and installers.

**Comment by mbrodala** [comment]
@kherge I didn't actually notice that the original request was about embedding the signature. This is what Composer does and it is pretty pointless IMO since one can easily exchange the signature after tampering with the PHAR this way. Thus yes, yours is the way to go in this case. Normally the signature is embedded and the PHAR cannot be executed without the public key for verification. (Maybe I'm confusing what Composer does here.)

Thus one would get your public key once and retrieve the signature of the Box release to run in the end? If one doesn't care about security, he can download/install the Box release as usual without any difference?

**Comment by kherge** [comment]
I'm thinking that I'll upload the detached signature with each release. I'll then include it in the manifest and modify the installer to download the signature and check it if GPG is installed. I'll also have to modify the `update` command to do a verification if GPG is installed.

**Comment by mbrodala** [comment]
@kherge Hm, that sounds like the installer will become the single point of failure. How can I trust the installer to do the right thing? I think a solution more closer to the regular PHAR signing would be preferable to have a safe workflow.

**Comment by kherge** [comment]
I have opted to upload the GPG signature with each release, and added my public key to the MIT key server. Information has been added to the README.

**Comment by mbrodala** [comment]
@kherge Can you go a bit more into detail in the README? I for myself wouldn't know how to continue after importing your key.
