### ISSUE TITLE
Cann't Build phar file

### ISSUE THREAD

**Issue by nahid** [box-project/box2#127]
I want to build a phar file. When I run command `box build` it display an error look like this.

``` shell
[UnexpectedValueException]                                                                       
  creating archive "/Users/nahid/myphar/myphar.phar" disabled by the php.ini setting phar.readonly
```

I set `phar.readonly=Off`also but it does not work

**Comment by kherge** [comment]
Can you run `php -i` and share the output? It looks like that the INI setting is not being applied to the environment you are using.

**Comment by juanmaa1414** [comment]
Old question but the problem maybe can be the semicolon comment character in that line of php.ini.
