### ISSUE TITLE
My ignore list doesn't work

### ISSUE THREAD

**Issue by ptondereau** [box-project/box2#128]
Hello,
Thanks for your great product !

I've got a problem with my box.json : 

```
{
  "alias": "my-cli.phar",
  "chmod": "0755",
  "directories": [
    "src",
    "bin",
    "vendor"
  ],
  "files": [],
  "finder": [
    {
      "in": "vendor",
      "exclude": [
        "myclabs",
        "phpspec",
        "phpdocumentor",
        "phpunit",
        "phpunit-test-case",
        "Tester",
        "Tests",
        "tests",
        "yaml"
      ]
    }
  ],
  "git-version": "package_version",
  "main": "my-cli.php",
  "output": "my-cli.phar",
  "web": false,
  "stub": true,
  "compression": "BZ2"
}
```

Indeed, while I compile with this command: `php -d phar.readonly=0 box.phar build`
I can see in phar archive that it compress my excluded files and it seems it doesn't care about my box.json...

Any ideas ?

**Comment by kherge** [comment]
When you build your phar, do the other settings seem to work? The most obvious sign would be that the phar is generated using the name you set in "output".

**Comment by ptondereau** [comment]
Yes, it outputs it with the name set in my json

**Comment by kherge** [comment]
Is your project publicly available? I'd like to see the output of the build process myself.

**Comment by ptondereau** [comment]
Unfortunaly, no. It's private... Sorry

**Comment by kherge** [comment]
Could you please recreate the issue with a new project that you can share? It doesn't have to be anything elaborate, it could be as little as just having a `composer.json` and `box.son` file.

**Comment by ptondereau** [comment]
Thank you for your help but I solved my problem:

I've just deleted my `composer.lock` and run `composer update`

It now compress perfectly !
