### ISSUE TITLE
Allow usage with Symfony 3.x

### ISSUE THREAD

**Issue by aik099** [box-project/box2#146]
Right now Symfony components at 2.x version are locked in `composer.json`. There shouldn't be any harm in changing their version from `~2.1` to `~2.1|~3.0`. This would allow usage of Symfony 3 alongside with this library on same project.

**Comment by Anahkiasen** [comment]
👍  for this, having the same issue

**Comment by jameshalsall** [comment]
There's an open PR for this #144.

**Comment by kherge** [comment]
I'm sorry for the wait, but [2.7.3](https://github.com/box-project/box2/releases/tag/2.7.3) is out now with support for installing with newer Symfony components.
