### ISSUE TITLE
the website should enforce HTTPS

### ISSUE THREAD

**Issue by stof** [box-project/box2#150]
Github now has a feature to enforce HTTPS usage on `*.github.io` websites. This should be done here, as you use it as a distribution way

**Comment by kherge** [comment]
The HTTPS setting has been checked, and I have updated the URLs where I have found them. A new release has been made available (2.7.4) that uses the HTTPS URL to download the update manifest.

Thanks for the suggestion, and please let me know if you bumped into any issues as a result of this change!

**Comment by stof** [comment]
great
