### ISSUE TITLE
Phar file for v2.7.4 is broken [unexpected T_STRING in Process.php]

### ISSUE THREAD

**Issue by keradus** [box-project/box2#151]
Box project claims to work under [PHP 5.3.3](https://github.com/box-project/box2/blob/2.0/composer.json#L18)

This is not true anymore for v2.7.4 phar file, v2.7.2 phar file is working.
Failing example: https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/152603392#L963

The reason is the way that box phar file was built - it uses too new deps, exactly Symfony v3.x components (in general it allows v2 || v3), which won't run under PHP 5.3.3. I would say that build is done on newer PHP version. It could be avoided by updating component deps before building the box phar with `"platform": {"php": "5.3.3"}` in `composer.json` file ([example](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/.travis.yml#L48-L52)).

Sadly, I cannot help more as phar file is built outside Travis (probably locally by project maintainers).

**Comment by weitzman** [comment]
Also broken on PHP 5.4 AFAICT - https://travis-ci.org/drush-ops/drush/jobs/162482903

**Comment by glensc** [comment]
corrected `.travis.yml` link: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v1.11.8/.travis.yml#L48-L52

(never use links to source code lines using branch, use tag or git commit)

**Comment by keradus** [comment]
is this project not maintained ?

**Comment by kherge** [comment]
[box-2.7.4-3-g8ce371c.phar.zip](https://github.com/box-project/box2/files/644858/box-2.7.4-3-g8ce371c.phar.zip)

Can you guys please give this build a try?

I took the suggestion of applying the `platform` config setting and re-installed all of the vendor packages after resetting the lock file, hopefully it works on 5.3 now. If it does, I'll tag a new release and upload a new archive for download.

**Comment by glensc** [comment]
@kherge try how? where's the .phar to test with?

**Comment by kherge** [comment]
@glensc Ack, I messed up my last post. I fixed it now, the link should be at the top of my previous post.

**Comment by glensc** [comment]
i can confirm the phar works

```
$ php53 -d phar.readonly=0 box-2.7.4-3-g8ce371c.phar build -c ~/scm/eventum/cli/box.json 
Building...

$ php53 -d phar.readonly=0 box-2.7.4.phar build -c ~/scm/eventum/cli/box.json 
Building...
PHP Parse error:  syntax error, unexpected T_STRING in phar:///home/glen/Downloads/box-2.7.4.phar/src/vendors/symfony/process/Process.php on line 538
PHP Stack trace:

```

**Comment by glensc** [comment]
but, why not build the .phar from travis?

you can build the .phar from travis and upload it automatically to github release when tag is made:
- [documentation](https://docs.travis-ci.com/user/deployment/releases)
- [example using encrypted string](https://github.com/eventum/scm/blob/v3.1.2/.travis.yml)
- [example using secure variable](https://github.com/eventum/eventum/blob/679766757a73b790bde23047f503c6d90684cdb6/.travis.yml)

encrypted string is probably securer because it does not "leak" from build logs because it's already public (committed to repository). secure variable may leak if you print out env variables in your build. travis-ci implentation is weird, they should replace secure variables with `***` but it doesn't (always?) work.

**Comment by keradus** [comment]
phar file is signed here (at least it was once), not easy to manage private gpg key on travis

**Comment by kherge** [comment]
Thank you @glensc!

@keradus Could you also confirm that it works for you?

**Comment by glensc** [comment]
@kherge you can sign it offline (downloading copy) after you have verified contents. i do that practice myself.

**Comment by keradus** [comment]
```
D:\tmp
λ php --version
PHP 5.3.29 (cli) (built: Aug 15 2014 19:17:16)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies

D:\tmp
λ php box-2.7.4-3-g8ce371c.phar --version
Box version 2.7.4-3-g8ce371c build 8ce371cdc1f0005e087e9ca5c265b52b5f560fd4
```

Thank you @kherge 
I hope new versions will be safe from that bug ;)
I'm closing a ticket.

-------

@glensc personally i see making an artifact by travis, upload it to gh by travis, then download it, sign it and reuplaod it a little workaround... not needed

**Comment by glensc** [comment]
@keradus letting travis make the phar, i see:
1. consistent results, developer may change their default php version and hence this issue
2. making release is easy than just git tag & push

why you need to re-upload? the signature is detached.

also you need actually invoke box build, --version did not trigger this bug.
