### ISSUE TITLE
Sign git tags & commits

### ISSUE THREAD

**Issue by rugk** [box-project/box2#158]
You should consider signing git commits & releases.

* [onionshare#221 (comment)](https://is.gd/7vU4oK)
* It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
* Here is GitHub's help for this: https://help.github.com/articles/generating-a-gpg-key/
* And here is how you can properly sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

As you already have a PGP key, this should not be difficult for you. At least tags should be signed, so one can also use the verified(!) source to built the application by themselves.

**Comment by kherge** [comment]
I'm doing this for other repositories, but I'll start with this one.

I just enabled `commit.gpgsign` on my copy of the repos. Next commits will be signed.

Thanks!

**Comment by rugk** [comment]
Do not forget to enable tag singing. 

Tip:
```
[alias]
   tag = tag -s
```

**Comment by kherge** [comment]
[The update to the read me was signed using `git config commit.gpgsign true`.](https://github.com/box-project/box2/commit/6640e38a4d9c8809e4db9174d2e6ba52092a2292)

😃

**Comment by rugk** [comment]
Yeah, I know. 😃 (In case this is a reply to my previous comment: There is a difference between tag and commit signing)

**Comment by kherge** [comment]
Woops, my mistake!
