### ISSUE TITLE
Improve PGP key

### ISSUE THREAD

**Issue by rugk** [box-project/box2#159]
* do not use short IDs: https://evil32.com/
* add your fingerprint somewhere for verification or just use the full fingerprint in the command
* (possibly) also upload your key somewhere, which is not on your keyserver

**Comment by kherge** [comment]
Wow, thanks for the tips!

How does the following look as a replacement for that part in the readme?

---

You can find [kherge's GPG on keybase.io](https://keybase.io/kherge).

    32E4 B747 57B1 D652 34FC 389F 293D 7712 4151 5FE8

**Comment by rugk** [comment]
Looks good to me. 👍

**Comment by kherge** [comment]
Thanks for your help!
