### ISSUE TITLE
Extract class is always included & causes error

### ISSUE THREAD

**Issue by rugk** [box-project/box2#161]
This is always included even if I do not include `extract` in my JSON or set it to `false`:

```php
if (in_array('phar', stream_get_wrappers()) && class_exists('Phar', 0)) {
Phar::interceptFileFuncs();
set_include_path('phar://' . __FILE__ . PATH_SEPARATOR . get_include_path());
Phar::webPhar(null, $web);
include 'phar://' . __FILE__ . '/' . Extract_Phar::START;
return;
}
```

Also the `Extract_Phar::START` somehow evaluates to `index.php`, which is a non-existent file in the .phar.
This is my repo (including the box.json): https://github.com/rugk/threema-msgapi-sdk-php/tree/536457329376dc657cb02a558c9dd8d802af2b67

**Comment by rugk** [comment]
The error is shown here:
```
PHP Warning:  include(phar:///[…]/threema-msgapi-sdk-php/threema_msgapi.phar/index.php): failed to open stream: phar error: "index.php" is not a file in phar "[…]/threema-msgapi-sdk-php/threema_msgapi.phar" in […]/threema-msgapi-sdk-php/threema_msgapi.phar on line 9
PHP Stack trace:
PHP   1. {main}() […]/threema-msgapi-sdk-php/threema-msgapi-tool.php:0
PHP   2. include() […]/threema-msgapi-sdk-php/threema-msgapi-tool.php:15
PHP Warning:  include(): Failed opening 'phar://[…]/threema-msgapi-sdk-php/threema_msgapi.phar/index.php' for inclusion (include_path='phar://[…]/threema-msgapi-sdk-php/threema_msgapi.phar:.:/usr/share/php:/usr/share/pear') in […]/threema-msgapi-sdk-php/threema_msgapi.phar on line 9
PHP Stack trace:
PHP   1. {main}() […]/threema-msgapi-sdk-php/threema-msgapi-tool.php:0
PHP   2. include() […]/threema-msgapi-sdk-php/threema-msgapi-tool.php:15
[[ the error below is just a result of the failed including of the .phar file ]]
PHP Fatal error:  Class 'Threema\Console\Run' not found in […]/threema-msgapi-sdk-php/threema-msgapi-tool.php on line 18
PHP Stack trace:
PHP   1. {main}() […]/threema-msgapi-sdk-php/threema-msgapi-tool.php:0
``

**Comment by kherge** [comment]
This part of the default stub generated by the `phar` extension, not by Box. Unfortunately, the `extract` option has no effecton it.

Have you tried using a stub with no content?

**Comment by rugk** [comment]
I am not using any stub at all. [I've set it](https://github.com/rugk/threema-msgapi-sdk-php/blob/0e1d821f617d5cc4da406f5ed4b15b98fa2decf4/box.json#L18) to `false`. (and even when it is not set as previously, it should be false by default) If box creates one anyway, that's bad.

**Comment by kherge** [comment]
Sorry for the confusion. Box does not set a default stub, [the `phar` extension does](http://php.net/manual/en/phar.fileformat.stub.php) (the extension is used to create phars).

What I was suggesting is that you *do* create a stub, but leave it completely empty. Actually, you may need something like this at minimum:

```php
<?php __halt_compiler(); ?>
```

Then you would tell box you want to use that empty stub.

```json
{
    "stub": "myEmptyStub.php"
}
```

**Comment by rugk** [comment]
But I've already set "stub" to "false", so box should prevent phar from creating a stub - IMHO. Otherwise the setting is quite useless.

I'll try to do the steps you proposed.

**Comment by kherge** [comment]
If you run `box build --help`, you will see a description of the configuration options that are available.

```
The stub (string, boolean) setting is used to specify the location of a
 stub file, or if one should be generated. If a path is provided, the stub
 file will be used as is inside the Phar. If true is provided, a new stub
 will be generated. If false (or nothing) is provided, the default stub
 used by the Phar class will be used.
```

I understand what you're saying though, and this is something I am hoping to address with the next version of Box.

**Comment by rugk** [comment]
Okay, now creating works all fine, but see this error:

```console
$ box info threema_msgapi.phar


                                                                                                   
  [UnexpectedValueException]                                                                       
  internal corruption of phar "[…]/threema-msgapi-sdk-php/threema_msgapi.phar  
  " (__HALT_COMPILER(); not found)                                                                 
                                                                                                   


info [-l|--list] [--metadata] [-m|--mode[="..."]] [phar]

```

Also when I try to include it in another file:
```console
$ ./threema-msgapi-tool.php   
PHP Fatal error:  Class 'Threema\Console\Run' not found in […]/threema-msgapi-sdk-php/threema-msgapi-tool.php on line 18
PHP Stack trace:
PHP   1. {main}() […]/threema-msgapi-sdk-php/threema-msgapi-tool.php:0
```

**Comment by kherge** [comment]
You cannot autoload classes from the phar without setting the stub.

I noticed that you have `main` configured to load your autoloader. For this configuration option to work, you will need to have Box generate the stub for you.

**Comment by rugk** [comment]
That's strange. I know a phar for an [older version of the project](https://github.com/rugk/threema-msgapi-sdk-php/releases/download/v1.1.7/threema_msgapi.phar), which does not need all this. There is no strange stub and you can just do `include 'threema_msgapi.phar';`.

**Comment by rugk** [comment]
Any idea how I can create this simple .phar?

**Comment by rugk** [comment]
My bad. I did not understand the concept of stubs… Sorry.
