### ISSUE TITLE
What does "stub": true do?

### ISSUE THREAD

**Issue by georgy7** [box-project/box2#175]
And is there anywhere verbose documentation about all the options of `box.json`.

**Comment by kherge** [comment]
Hi @georgy7, you can find full documentation by running `box help build`.

Other information can be found on the website ([link](https://box-project.github.io/box2)).

**Comment by georgy7** [comment]
Hi @kherge.
I read the web page, but it does not explain what is stubs ("custom stubs", "stubs in existing Phars").
I don't get, what is this. And `box help build` did not help.

**Comment by georgy7** [comment]
Ok, this is something, that loads code. 🤔
http://fi2.php.net/manual/en/phar.fileformat.stub.php

**Comment by georgy7** [comment]
Thanks, but I still think, this project needs more documentation.

**Comment by theofidry** [comment]
@georgy7 you can find a fork at https://github.com/humbug/box where I attempted to make the documentation a bit more exhaustive. It still is missing some bits which are more specific to PHARs (which IMO shouldn't be in the official PHP doc) but I hope has been improved over Box2
