### ISSUE TITLE
box build: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by flythenimbus** [box-project/box2#177]
OS: Windows 10
PHP: 7.3
CLI: PowerShell

When I run `box build` I get the following error:

```
box build
Building...



  [ErrorException]
  count(): Parameter must be an array or an object that implements Countable



build [-c|--configuration="..."]
```

Advice would be appreciated.

**Comment by theofidry** [comment]
Hello, my advice would be to try out [Box3](https://github.com/humbug/box) instead which besides offering various improvements is actively maintained :)

If you already are using Box2, there is [an upgrade guide](https://github.com/humbug/box/blob/master/UPGRADE.md#from-27-to-30) and if other problems are encountered just feel free to open an issue :)

**Comment by flythenimbus** [comment]
Thanks! It's kinda misleading to use that package as it's not called Box**3**. When searching around I thought that Box2 is the latest version. @theofidry

**Comment by theofidry** [comment]
>It's kinda misleading to use that package as it's not called Box3

Indeed, but at the same time I don't really want to create a new repo for Box 4 when it will come out :) I just don't have control on the box2 repository so there is not much I can do.
