### ISSUE TITLE
Files added to the PHAR by "finder-bin" get white-space and comments removed

### ISSUE THREAD

**Issue by CHH** [box-project/box2#29]
First of all, this project has saved me countless hours getting PHAR packaging of PHP apps right :smile: .

This could also be my own error, being to dumb to configure it correctly.

I have some PHP files which I want to add to the PHAR verbatim via `finder-bin`, though comments and white space get removed.

My `box.json` is at https://github.com/CHH/spark/tree/master/box.json

**Comment by ghost** [comment]
I think I found the problem. I'll fix it today and release an update.

**Comment by ghost** [comment]
I'm waiting for Travis-CI to give me the green light before I release an update.

**Comment by ghost** [comment]
Update 1.0.3 released.

Hope this fixes the issue you're having!

**Comment by CHH** [comment]
I will check it out! Thanks for looking into it :smile:

**Comment by CHH** [comment]
Thanks! It works now.

**Comment by ghost** [comment]
Awesome, and glad I could help!
