### ISSUE TITLE
Detect phar.readonly=1 setting in installer

### ISSUE THREAD

**Issue by Seldaek** [box-project/box2#4]

**Comment by ghost** [comment]
(Oops, ignore the second commit.)

Users will now be warned when using the installer script that the `phar.readonly` option is enabled.  If they attempt to use Box commands such as `create`, the `Phar` class itself will throw an exception explaining that this INI setting is enabled.

**Comment by ssanders** [comment]
```
php -d phar.readonly=0 box.phar build
```
