### ISSUE TITLE
Something like git-version that always returns the full commit hash

### ISSUE THREAD

**Issue by simensen** [box-project/box2#42]
Maybe something like `git-commit`? This could be useful for people who want to be able to track both the full commit hash in addition to the short/taggish looking thing that `git-version` currently supports.

**Comment by ghost** [comment]
Updated Box to support this: 5e1572179129c46d78793c78033cef70fe045a39

New `box.json` options:
- `git-commit` &mdash; The full commit hash.
- `git-commit-short` &mdash; The short commit hash.
- `git-tag` &mdash; The current tag.

I plan on releasing it as part of the 2.1 update.

If you clone Box or install `dev-master` using Composer, you can run `box build --help` to get more information on the new options.

**Comment by simensen** [comment]
Excellent! Not sure when I'll have a chance to test this out but good to know it is there. Thanks!

**Comment by ghost** [comment]
The 2.1 update has finally be released.
