### ISSUE TITLE
box.phar returns Hs?

### ISSUE THREAD

**Issue by kasperg** [box-project/box2#43]
When I try to run `box.phar` after installing the project using the installer the command always seems to return `Hs?`.

If I clone the master branch of the project, install dependencies using composer and finally run `php ./bin/box` I get the expected Symfony console application overview.

Is there a problem with the current `box.phar` or could it be something that is not configured right on my local system?

I'm using:
- OSX 10.8.3
- PHP 5.3.16

**Comment by ghost** [comment]
When you say installer command, do you mean this:

`curl -s http://box-project.org/installer.php | php`

**Comment by kasperg** [comment]
Sorry If not making myself clear.

The installer: `curl -s http://box-project.org/installer.php | php`

The command: `box.phar`

It is `box.phar` that always returns Hs?.

**Comment by ghost** [comment]
Sorry for all the questions!
1. Do you have any problems running other phars?
2. What output do you get when you run: `echo '<?php echo "Hello!\n";' | php`

Unfortunately I do not have a Mac, so I cannot get these answers myself.

**Comment by kasperg** [comment]
> Do you have any problems running other phars?

I'm running `composer` installed through [homebrew](http://mxcl.github.io/homebrew/) without problems but that got me thinking. I checked out the actual command used to invoke composer and here `-d detect_unicode=Off` is added to the command.

Running `php -d detect_unicode=Off box.phar` solves the problem. [Apparently the `detect_unicode` setting is a known issue on OSX](http://jonathanmh.com/composer-and-the-php-ini-on-mac-os-x/).

Perhaps it is worthwhile adding a check for this in the installer?

Anyhow: Thans for the help. I look forward to try out Box!
