### ISSUE TITLE
box-project.org is down returning 404

### ISSUE THREAD

**Issue by salimane** [box-project/box2#46]
box-project.org is down returning 404 meaning impossible to install box. Is there a way to download directly box.phar ?
Thanks

**Comment by ghost** [comment]
Huh, I'll have to investigate that when I get the chance (today).

You can find all Box downloads at [Bitbucket](http://bitbucket.org/kherge/php-box/downloads).

**Comment by ghost** [comment]
I triggered GitHub's automatic page builder to see if that would clear things up.

It appears to be working again on my end.

Could you please check if it is working for you?

**Comment by salimane** [comment]
yep it's now working again.
thanks
