### ISSUE TITLE
Consider Added support to map file

### ISSUE THREAD

**Issue by lyrixx** [box-project/box2#47]
Hello. I'm trying your library. It seems cool, thanks.
But I have an issue.

I use composer, with the native autoloader, but I use a mount point like [that](https://github.com/sensiolabs/SensioLabsConnectBundle/blob/master/composer.json#L18-L23) This is not my project, this is just a sample.

My issue is that the autoloader can find class a the root of my project. But If I hack and copy the lib to the `target-dir`, it works. 

So it could me very nice to add a new option: a map between real path, and phar path:

```
"map": {
  "src": "SensioLabs/Bundle/ConnectBundle"
}
```

**Comment by ghost** [comment]
If I understand you correctly, I think this could be a great feature to add.

To make sure I got it right, I would just like to repeat your suggestion.

The map:

``` json
{
    "map": {
        "src": "SensioLabs/Bundle/ConnectBundle"
    }
}
```

would cause Box to copy or move the **src** directory contents into a different directory, **SensioLabs/Bundle/ConnectBundle**, inside the phar. I would alias the directory as a whole, but I don't think that phars support that.

Did I understand you correctly?

**Comment by lyrixx** [comment]
Yes, It's exactly that. (I re-repeat ;)) The folders "src" shound not be copied into "/src" but into "SensioLabs/Bundle/ConnectBundle".

**Comment by ghost** [comment]
I am currently trying to figure out how matching will be done.

I am thinking about using `fnmatch()`.

This configuration

``` json
{
    "map": {
        "src/*": "SensioLabs/Bundle/ConnectBundle"
    }
}
```

will match all files in `src/` while this configuration

``` json
{
    "map": {
        "src/*.php": "SensioLabs/Bundle/ConnectBundle"
    }
}
```

would only allow all PHP files in `src/`.

What do you think?

**Comment by lyrixx** [comment]
I think it's a good idea. I did not know `fnmatch` function. I learnt something today ;)
But do you know this function does not work on windows ? But i do not user windows :D

**Comment by ghost** [comment]
According to the [change log](http://us1.php.net/fnmatch), it is available on Windows starting with PHP 5.3.

I confirmed this with my installation of PHP 5.3 on Windows 7.

Since I will only be supporting PHP 5.3.3 and newer, it should be available.

I am hoping to get the new version of Box (with this feature) out later today.

**Comment by ghost** [comment]
Man, sorry about the delays.

Had to get a new SSD for my main rig, for some reason it stopped being detected on boot.

I just got it up and running again today.

The upside about this is that I got to thinking about this issue a little more.

I changed my mind about `fnmatch()`, thinking its a bad idea now.

Whenever `fnmatch()` matches a path, Box would have stored the file in the target directory.

This would have made files such as `src/Some/Sub/Directory/Test.php` into `src/Test.php`.

I'm thinking about going back to your suggestion.

How should your file path matching work?

Would `map` only work for directories, files, relative/full paths?

**Edit:** I might have accidentally deleted your comment (some how).

**Comment by lyrixx** [comment]
No problem for the delay ;) And sorry for your SSD.

IHMO, a very simple matching is enought.

BTW, the real project where I wanted to use your project is now open source: https://github.com/sensiolabs/insight. You can try to make a working phar with it.
It's easy to test: just run the `bin/insight` file. The first issue you will meet is this issue.

**Comment by ghost** [comment]
Okay, it finally looks like I have something viable.

[Here](https://bitbucket.org/kherge/php-box/downloads/box-2.1.0-7-ga1e69aa.phar) is a test version of Box with mapping support.

(I am going to delete that file once a stable release is out.)

Use this configuration file:

``` json
{
    "chmod": "0755",
    "directories": ["."],
    "main": "bin/insight",
    "map": {
        "Cli": "SensioLabs/Insight/Cli",
        "Sdk": "SensioLabs/Insight/Sdk"
    },
    "output": "insight.phar",
    "stub": true
}
```

Let me know how it works for you.

If it works the way you expect, I will then finish up by writing a bunch of tests and releasing an update to Box.

**Comment by lyrixx** [comment]
Thanks. 

But the phar does not work:

```
>[~/dev/product/insight-sdk](master %) php box-2.1.0-7-ga1e69aa.phar 
PHP Warning:  require(phar:///home/greg/dev/product/insight-sdk/box-2.1.0-7-ga1e69aa.phar/bin/box): failed to open stream: phar error: "bin/box" is not a file in phar "/home/greg/dev/product/insight-sdk/box-2.1.0-7-ga1e69aa.phar" in /home/greg/dev/product/insight-sdk/box-2.1.0-7-ga1e69aa.phar on line 10
PHP Stack trace:
PHP   1. {main}() /home/greg/dev/product/insight-sdk/box-2.1.0-7-ga1e69aa.phar:0

Warning: require(phar:///home/greg/dev/product/insight-sdk/box-2.1.0-7-ga1e69aa.phar/bin/box): failed to open stream: phar error: "bin/box" is not a file in phar "/home/greg/dev/product/insight-sdk/box-2.1.0-7-ga1e69aa.phar" in /home/greg/dev/product/insight-sdk/box-2.1.0-7-ga1e69aa.phar on line 10

Call Stack:
    0.0057     201664   1. {main}() /home/greg/dev/product/insight-sdk/box-2.1.0-7-ga1e69aa.phar:0

PHP Fatal error:  require(): Failed opening required 'phar:///home/greg/dev/product/insight-sdk/box-2.1.0-7-ga1e69aa.phar/bin/box' (include_path='.:/usr/share/php:/usr/share/pear') in /home/greg/dev/product/insight-sdk/box-2.1.0-7-ga1e69aa.phar on line 10
PHP Stack trace:
PHP   1. {main}() /home/greg/dev/product/insight-sdk/box-2.1.0-7-ga1e69aa.phar:0

Fatal error: require(): Failed opening required 'phar:///home/greg/dev/product/insight-sdk/box-2.1.0-7-ga1e69aa.phar/bin/box' (include_path='.:/usr/share/php:/usr/share/pear') in /home/greg/dev/product/insight-sdk/box-2.1.0-7-ga1e69aa.phar on line 10

Call Stack:
    0.0057     201664   1. {main}() /home/greg/dev/product/insight-sdk/box-2.1.0-7-ga1e69aa.phar:0
```

Does I miss something ?

**Comment by ghost** [comment]
Agh, sorry, that is my fault.

[Here](https://bitbucket.org/kherge/php-box/downloads/box-lyrixx.phar) is another build.

**Comment by lyrixx** [comment]
You're fast ;) 

It's works. Thanks.

I have an issue but it is not related to you.
May be you know how to fix that.
I use `__DIR__` and I write to a file and I got this error:

```
  [UnexpectedValueException]                                                                                                                         
  The stream or file "phar:///home/greg/dev/product/insight-sdk/insight.phar/SensioLabs/Insight/Cli/../insight.log" could not be opened: failed to   
  open stream: phar error: open mode append not supported     
```

I think I should use `getcwd`.

https://github.com/sensiolabs/insight/blob/master/Cli/Application.php#L55

**Comment by ghost** [comment]
While using **DIR** and **FILE** inside any phar, you will get a `phar://` URI.

From what the error is telling me, you are trying to write to a file inside the phar, which I don't think is possible without using the `Phar` class.

Are you trying to write to a log file in the same directory as `insight.phar`, and not actually inside the phar?

**Comment by ghost** [comment]
Sorry that was supposed to read `__DIR__` and `__FILE__`.

(iPhone)

**Comment by lyrixx** [comment]
I do not want to write in the phar ;) I think  `getcwd` is what I really
want to do ;)

Thanks

**Comment by ghost** [comment]
You're welcome!

I will try and release an update either tonight or tomorrow.

**Comment by ghost** [comment]
Okay, 2.2 released!

You can see the release notes here: https://github.com/kherge/Box/releases/tag/2.2.0

I actually had to change the way files were mapped, but not too much:

``` json
{
    "chmod": "0755",
    "directories": ["."],
    "main": "bin/insight",
    "map": [
        {"Cli": "SensioLabs/Insight/Cli"},
        {"Sdk": "SensioLabs/Insight/Sdk"}
    ],
    "output": "insight.phar",
    "stub": true
}
```

The change was made to preserve the order in which the replacements were provided. JSON does not necessarily respect the order, so theoretically `Sdk` would sometimes come in before `Cli`. While this may not matter for your project, it could mean the difference between a having a working phar or rage quitting in someone else's project.

Thanks for your help!
