### ISSUE TITLE
Can't install on php 5.3.10 with Suhosin-Patch

### ISSUE THREAD

**Issue by r8** [box-project/box2#51]
Box installer doesn't work on php 5.3.10 with Suhosin patch

As far as I understand adding `suhosin.executor.include.whitelist = phar`  will work only for Suhosin extension. Suhosin patch seems to ignore this keyword.

After I commented out suhosin check, installed worked as expected, so it seems that white listing isn't required for patch. 

Composer installer checks white list only for extension: composer/getcomposer.org@9b43609

Also similar issue can be seen here https://github.com/symfony/symfony/issues/5444#issuecomment-8363693

**Comment by ghost** [comment]
Could you please try again?

**Comment by r8** [comment]
Thanks, worked like a charm!

**Comment by ghost** [comment]
Awesome
