### ISSUE TITLE
installer.php not always available.

### ISSUE THREAD

**Issue by h4cc** [box-project/box2#58]
My travis builds are failing recently, because the http://box-project.org/installer.php is sometimes not available.

Example output from curl:

```
$ curl --verbose http://box-project.org/installer.php
* About to connect() to box-project.org port 80 (#0)
* Trying 204.232.175.78... connected
> GET /installer.php HTTP/1.1
> User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: box-project.org
> Accept: */*
> 
< HTTP/1.1 302 Found
< Connection: close
< Pragma: no-cache
< cache-control: no-cache
< Location: /installer.php
<
* Closing connection #0
```

Would a different call to curl fix this?

Maybe using '--location' or '--retry 3'.

**Comment by ghost** [comment]
Please give this one a try:

```
curl -Ss http://box-project.org/installer.php | php
```

If that works for you, I will update the README to use this instead.

**Comment by h4cc** [comment]
Does not work :(

Maybe have look at my travis job, its nearly constantly failing: https://travis-ci.org/h4cc/depicter/jobs/16726031

**Comment by ghost** [comment]
Hmm, please give this one a try:

```
curl -Ss http://box-project.org/installer.php 2> error.log | php
```

I tried that one and it worked, not sure why though.

**Edit:** If you don't want an empty error log to be generated, you can use this line instead:

```
curl -Ss http://box-project.org/installer.php 2> /dev/null | php
```

**Comment by h4cc** [comment]
There is no error to find. curl does what it sould.
curls default is to fetch the page once and output the response body.

The github page response this:

```
HTTP/1.1 302 Found
...
Location: /installer.php
```

curl is not instructed to follow rediects, so it simply prints the empty reponse body of the 302 reponse.

The problem mostly occures, when using Travis-Ci. But the same error has been on my laptop too.
I think its a glitch when using the Github Pages CDN. The 302 response on the resource itself may be added to provide some time the build up the cache for not yet cached content on the cdn.

_Hint:_
The composer installer is not hosted on Github Pages, so he does not have the same problem.

**Comment by ghost** [comment]
I think you're right, GitHub Pages is acting weird.

I knew that there weren't any errors, but for some reason it started working when I simply redirected the error output. It appears that it actually had no effect and it was just the timing.

Fortunately cURL offers the ability to follow redirects, so try this command:

```
curl -LSs http://box-project.org/installer.php | php
```

**Comment by h4cc** [comment]
The "-L" option works. (http://curl.haxx.se/docs/manpage.html#-L)

Although i was not sure if it might be a security breach. But loading Code from the net and executing it directly might be already questionable enough.

**Comment by ghost** [comment]
I'll update the README and close this issue.

Alternatively, you can simply do a global install of Box:

```
composer global require kherge/box=2.*
```
