### ISSUE TITLE
Error on adding the same file twice

### ISSUE THREAD

**Issue by empi89** [box-project/box2#63]
I am just wondering how to show an error message if users add the same file twice to the phar, e.g. by specifying a directory and including files of the directory via the finder method too. Currently there is only a call to addFile (https://github.com/kherge/Box/blob/2.0/src/lib/KevinGH/Box/Command/Build.php#L668) without checking if the file is already in. The underlying library does not hold a state which files are in the phar (https://github.com/herrera-io/php-box/blob/master/src/lib/Herrera/Box/Box.php#L117) and could not check either. 

Maybe it would be good to change the library to store all added files in an array and expose a method like getFiles() or isFileOnPath($path)?

**Comment by ghost** [comment]
Unless there is an easy way to fix the same file being added twice or more, I'm not sure I'd support a change like this. I can easily see this turning into a configuration nightmare.
