### ISSUE TITLE
add -sS on installation instructions

### ISSUE THREAD

**Issue by cordoval** [box-project/box2#65]

**Comment by ghost** [comment]
I noticed that the website was outdated.

Is that what you are referring to?

I have rebuilt the website using the new README file.

**Comment by cordoval** [comment]
is also sad that the readme is gone,t hat shouldn't be

also what is your tweeter handle? I was trying to find out if your library was good to use for Gush 

https://github.com/cordoval/gush/issues/25#issuecomment-33288380 we went for a library for semver but now i am not sure

you make it confusing with that org herrera ... are you herrera? :baby:

**Comment by ghost** [comment]
1. The README is [still there](https://github.com/kherge/Box/tree/2.0), just on a different branch (I'm working on 3.0).
2. My Twitter handle is [kherge](http://twitter.com/kherge).
3. I hope it works out for you, please let me know if you have questions.
4. I own the Herrera.io and Phine organizations. :smiley:

**Comment by cordoval** [comment]
what is the L for? :baby:

**Comment by ghost** [comment]
It tells cURL to [follow redirects](http://curl.haxx.se/docs/manpage.html#-L).

**Comment by cordoval** [comment]
oh nice, i needed that back when i was doing bit.ly links, now i am doing it directly so i guess it is not needed, thanks
