### ISSUE TITLE
«shebang: false» option

### ISSUE THREAD

**Issue by velosipedist** [box-project/box2#66]
When i include .phar as standalone toolbox (similar with Guzzle, for example), i have unnecessary shebang output.

Why not to extend "shebang" option with possible `false` value? Now it is treated as invalid.

**Comment by ghost** [comment]
I agree that it would be a good idea to support removing the shebang line.

Did you want to submit a PR?

**Comment by velosipedist** [comment]
Yes, i did, but not earlier than saturday. Did'nt expect such :light_rail:  reaction :)

**Comment by ghost** [comment]
No rush! I just try to respond quickly so people don't feel ignored.

:smile:

**Comment by velosipedist** [comment]
Thanks, i feel :)
