### ISSUE TITLE
Make shebang line optional.

### ISSUE THREAD

**Issue by ghost** [box-project/box2#68]
[This definition](https://github.com/kherge/Box/blob/master/src/lib/KHerGe/Box/Config/Definition.php#L400) should be changed so that `null` or empty string is acceptable. The result should be that no shebang line is generated for the stub.

(Credit to @velosipedist in #66 for the idea.)

**Comment by oschwald** [comment]
I am still getting the shebang line with 2.4.4. When I set "shebang" to null or the empty string, I get a JSON validation error.

**Comment by oschwald** [comment]
I apologize. I didn't notice that this was only fixed in master, not the 2.0 branch.
