### ISSUE TITLE
how to support self-update command?

### ISSUE THREAD

**Issue by cordoval** [box-project/box2#69]

**Comment by ghost** [comment]
Sorry, I don't understand.

Could you please provide more detail? What do you mean by support?

**Comment by cordoval** [comment]
composer and other phars support self-update command to upgrade themselves

how can we do this with box?

**Comment by ghost** [comment]
The `box update` command updates the phar.

**Comment by cordoval** [comment]
for box or for the phars that are created with box?

**Comment by ghost** [comment]
Ah, I think I know what you mean now.

Box can update itself with `box update`. Box itself cannot, and probably will never provide this capability for other applications. However, there are other libraries that can do it for you. For the moment, the one I use for Box is [Amend](https://github.com/kherge/Amend).

**Comment by cordoval** [comment]
perfect thanks
