### ISSUE TITLE
git-commit is not replaced by commit hash

### ISSUE THREAD

**Issue by llaville** [box-project/box2#71]
Hello Kevin,

First thanks for this great tools. Really cool to use, even if there is only bundle docs.

Before to be able to build my first distrib version, I've tried many case, and found I problem on git commit hash feature.

It works fine if you've always the same placeholder open/close tag ( @ ).
But it's not always TRUE!

For history reason ( CVS ) the [@version phpdoc tag](http://phpdoc.org/docs/latest/references/phpdoc/tags/version.html) uses itself the open / close dollar delimiter.

So on all sources with such code 

```
/**
 * @version  GIT: $Id$
 */
```

there are no replacements with a box.json  "git-commit": "Id"

But on the second case

```
/**
 * @version  Release: @package_version@
 */
```

the replacement is ok with a box.json  "git-version": "package_version"

Hope my report is enough
Laurent

**Comment by llaville** [comment]
Of course you know where the problem is ?
https://github.com/kherge-old/Box/blob/2.0/src/lib/KevinGH/Box/Configuration.php#L826

It will be very if open/close delimiter are included in placeholders themself !

**Comment by ghost** [comment]
I'll support custom placeholders in the next version of Box.

**Comment by llaville** [comment]
That's cool : nice to hear it :)
