### ISSUE TITLE
Extract command does not works properly

### ISSUE THREAD

**Issue by llaville** [box-project/box2#76]
I've used today the `extract` command features 

```
Box version 2.4.4 build 71938bf622e230a58246a6b732b137eb4051a37a
```

I've tried to extract contents of an archive built with my [box.json](https://github.com/llaville/php-reflect/blob/v2/box.json) and box 2.4.4

I got all files but there were all still compressed. Probably because you don't checks if an archive is compressed or not in extract command [lines 86 to 105](https://github.com/kherge/php-box/blob/2.0/src/lib/KevinGH/Box/Command/Extract.php).

**Comment by ghost** [comment]
Do you have an example phar I can test with?

**Comment by llaville** [comment]
Of course, you can use :  
http://bartlett.laurent-laville.org/get/phpreflect-2.0.0RC2-6-ge55464a.phar

BTW, (and of course) when I remove the "compression": "GZ" option from my box.json, I got all files as expected.

**Comment by ghost** [comment]
Okay, I have a copy and taking a look at it. This is weeeeird so far.

**Comment by polothy** [comment]
Hit this as well, I think you need to use [PharData](http://php.net/manual/en/phardata.extractto.php) instead of Phar when extracting files from a compressed phar.

Edit: I tried PharData and it does not work.

**Comment by theofidry** [comment]
@polothy you can try `box extract` from https://github.com/humbug/box. I think there is a small bug there but should be easy to fix
