### ISSUE TITLE
'  failed to open stream: No such file or directory ' with laravel

### ISSUE THREAD

**Issue by ghost** [box-project/box2#77]
i want to build application with laravel and after i build it with 'box'
the box.json file ::

``` json
{
    "alias": "test.phar",
    "chmod": "0755",
    "directories": ["src/app", "src/public", "src/bootstrap"],
    "files": [
        "src/vendor/autoload.php"
    ],
    "finder": [{
        "name": "*.php",
        "exclude": ["Tests", "tests", "test-suite"],
        "in": "src/vendor"
    }],

    "git-version": "package_version",
    "main": "bin/index",
    "output": "bin/blog.phar",
    "stub": true
}
```

and run it from the command line the console print this error :

``` php
PHP Warning:  require(/vendor/laravel/framework/src/Illuminate/Foundation/start.php): failed to open stream: No such file or directory in phar:///opt/lampp/htdocs/phars/test/bin/blog.phar/src/bootstrap/start.php on line 60
PHP Stack trace:
PHP   1. {main}() /opt/lampp/htdocs/phars/test/bin/blog.phar:0
PHP   2. require() /opt/lampp/htdocs/phars/test/bin/blog.phar:10
PHP   3. require() phar:///opt/lampp/htdocs/phars/test/bin/blog.phar/bin/index:3
PHP   4. require_once() phar:///opt/lampp/htdocs/phars/test/bin/blog.phar/src/public/index.php:35
PHP Fatal error:  require(): Failed opening required '/vendor/laravel/framework/src/Illuminate/Foundation/start.php' (include_path='phar:///opt/lampp/htdocs/phars/test/bin/blog.phar/src/vendor/phpseclib/phpseclib/phpseclib:.:/opt/lampp/lib/php') in phar:///opt/lampp/htdocs/phars/test/bin/blog.phar/src/bootstrap/start.php on line 60
PHP Stack trace:
PHP   1. {main}() /opt/lampp/htdocs/phars/test/bin/blog.phar:0
PHP   2. require() /opt/lampp/htdocs/phars/test/bin/blog.phar:10
PHP   3. require() phar:///opt/lampp/htdocs/phars/test/bin/blog.phar/bin/index:3
PHP   4. require_once() phar:///opt/lampp/htdocs/phars/test/bin/blog.phar/src/public/index.php:35
```

and my directory structure :

``` bash
.
├── bin
│   ├── blog.phar      # the output
│   ├── index            # the main file
│   ├── index.php    ## to access the phar from the browser
│   └── storage
├── box.json
└── src
    ├── app
    ├── artisan
    ├── bootstrap
    │   ├── autoload.php
    │   ├── paths.php
    │   └── start.php
    ├── composer.json
    ├── composer.lock
    ├── CONTRIBUTING.md
    ├── phpunit.xml
    ├── public
    │   ├── favicon.ico
    │   ├── index.php         ## the main file for web app
    │   ├── packages
    │   └── robots.txt
    ├── readme.md
    ├── server.php
    └── vendor

```

where is my mistake ??

**Comment by ghost** [comment]
It looks like one of your `require()` paths doesn't work inside the phar.

Is your project available for me to look at?

**Comment by goslobanu** [comment]
Hi,

i have the same issue here (same failed to open file) and i don't manage to solve it.

did you find the issue ?

thx

**Comment by ghost** [comment]
Hi @goslobanu, unfortunately no.

From what I can tell, there is something wrong with the way the file is being included. Without knowing what that `require()` looks like, I can't say for sure.

**Comment by goslobanu** [comment]
Hi,

you can view the code by downloading/installing the latest version of laravel framework. i used an unmodified version of it and it didn't worked.

i would appreciate if you can help me.
thx

**Comment by ghost** [comment]
Can you please provide the Box configuration file you used for the default laravel framework?

**Comment by goslobanu** [comment]
Hi @kherge ,

here it is:

{
    "chmod": "0755",
    "directories" : ["app", "bootstrap", "vendor"],  
    "main": "artisan",
    "output": "artisan.phar",
    "stub": true
}

thx

**Comment by ghost** [comment]
This doesn't appear to be a problem with Box.

The `bootstrap/start.php` script access an index `path.base` that doesn't return a value.

Because the value is empty, it tries to load `/vendor/laravel/framework/src/Illuminate/Foundation/start.php` which starts at the root directory. This error message makes sense.

**Comment by goslobanu** [comment]
tnx for watching.

---

i found the issue/solution phar-ing laravel being as following:
- realpath() function was used inside laravel framework and causing the issue (this was reported also on php.net - Bug #52769   realpath not working inside phar)
- i solved this by modifying start.php with 

//GO change
//$app->bindInstallPaths(require **DIR**.'/paths.php');

//GO change
require **DIR**.'/paths.php';
$app['path'] = $paths['app'];
foreach (array_except($paths, array('app')) as $key => $value) {
    $app["path.{$key}"]  = $value;
}

and in paths.php: 
//GO change
return $paths = array(...

---

anyway i have a question for you: why phar-ing with your tool a project like laravel took about 10 minutes and with other tools like phing took about 6 seconds ?

tnx

**Comment by ghost** [comment]
I'm not sure how Phing works, so I'll take a guess.

Phing is simply packaging the files as a phar, while Box processes the files that are being packaged. A good way to check is to see the file size difference between the phars created by Phing and Box. If Phing's phar file is bigger than Box's, then it's confirmed as true. If you just need a super quick phar builder without any special handling, then it sounds like Phing might better suit your needs.

I'll close this issue because it sounds like the initial issue is resolved.  If you find anything else wrong, or want to address the performance issues, please open another issue.

**Comment by ghost** [comment]
thank @goslobanu for solving my problem . but when opening the phar from the terminal it is okay . i see artisan commands . in the other side when open it from the browser with script as runner like this :

``` php
    <?php

        require 'phar://artisan.phar/public/index.php';
```

in console it is show the index page but in the browser show

``` php
Error in exception handler.
```

**Comment by xtrasmal** [comment]
@alnour-altegani what is in your /bin/index if I may ask.
