### ISSUE TITLE
New feature: Build the new Box 3.0 with an EDA

### ISSUE THREAD

**Issue by llaville** [box-project/box2#78]
Hello,

I've built today a huge archive (1,1 Mb with GZ compression) (4 Mb without compression) and lot of files especially due to dependencies used. It took me 3 minutes to do so.

Here is my request : could you envisage to implement in next major version 3.0 of box an [EDA](http://en.wikipedia.org/wiki/Event-driven_architecture). Perharps with Symfony [EventDispatcher](http://symfony.com/doc/current/components/event_dispatcher/index.html).

It may be simple to implement a notification system at end of process, or just log content of files.

What do you think of this idea ?
Laurent

**Comment by ghost** [comment]
Actually, I had planned on doing just that!

Coupled with the use of Symfony's DependencyInjection component, I was aiming for far more flexibility on how the app can be used. With a configuration file, you can register event listeners or even swap out parts of the application's services with your own.
