### ISSUE TITLE
Where can I find the documentation?

### ISSUE THREAD

**Issue by ghost** [box-project/box2#81]
Despite any effort I made, I could not find an online documentation about the `box.json`.

**Comment by ghost** [comment]
Sorry about that, it's not really obvious.

If you run `php box.phar build -h`, you should see a complete listing of configuration options and what they do.

**Comment by ghost** [comment]
Can I somehow print that? It is hard to read long console messages on windows... :s

**Comment by ghost** [comment]
:\ Unfortunately you have to copy and paste it to a text file or something like that.

**Comment by velosipedist** [comment]
just `php box.phar build -h > help.txt`

**Comment by ghost** [comment]
thx, it took me about a minute to convert it into md...

**Comment by flip111** [comment]
I'm missing documentation too ... most of the options i don't understand what they do even though i've read the build help.
