### ISSUE TITLE
New feature: Support phar update

### ISSUE THREAD

**Issue by lyrixx** [box-project/box2#84]
Hello, 

It could be very nice to be able to trigger: `box update`. Because when the project is quite big, the phar compilation is slow ;) We already did a things like this, so it's possible...

**Comment by lyrixx** [comment]
oups, it already exists. Sorry for the noise.

**Comment by lyrixx** [comment]
Actually, this does not work on my computer.
I edit a file, then execute box update, the box tell me everything is up to date :(

**Comment by ssanders** [comment]
I think that updates Box; see http://box-project.org.

**Comment by ghost** [comment]
Yeah, unfortunately I named the Box app update command `update`, which will only update the Box app itself. In hindsight, I should've used a name like Composer's (`self-update`).

I think incremental building should be supported in the next version of Box.

**Comment by lyrixx** [comment]
Any new about this one?

**Comment by theofidry** [comment]
@lyrixx not sure it's still relevant, but I've forked it to update a couple of things and I'll move it to humbug/phar-updater (see https://github.com/humbug/box)

**Comment by lyrixx** [comment]
I don't need this feature anymore. Thanks
