### ISSUE TITLE
library phar

### ISSUE THREAD

**Issue by glensc** [box-project/box2#88]
i wanted to create a library phar, that i require and can use classes from that library.

but the shebang is forced, i can't turn it off:

```
$ php -r 'require_once "test.phar";'
#!/usr/bin/env php

$ 
```

i tried:
- `"stub": false` -> this created web app, do not want  that either
- `"shebang": false` -> this complained my json is not valid
- `"shebang": ""` -> this errored that shebang must start with `#!`

**Comment by ghost** [comment]
I can't believe I don't currently support this.

Adding it to the list of things to fix.

**Comment by oschwald** [comment]
I also ran into this issue. It'd be great to see it fixed.

**Comment by kherge** [comment]
Box 2.5.0 now supports this: https://github.com/box-project/box2/releases/tag/2.5.0

**Comment by oschwald** [comment]
:+1:
