### ISSUE TITLE
Error when building phar

### ISSUE THREAD

**Issue by bretrzaun** [box-project/box2#90]
Hello,
when I am trying to generate the example project I get the following error.

```
$ php box.phar build
Building...

  [PharException]
  unable to copy stub of old phar to new phar "/vagrant/apps/box2-example/example.phar"
```

I just installed the box.phar (without getting any errors) and cloned the example repo. 
What I am doing wrong ?

**Comment by kherge** [comment]
This doesn't appear to be an issue with Box, but the phar extension for PHP.

A little bit of digging and it looks like it has something to do with issues writing to the new archive file. Are you out of disk space, or not have permission to write to the target directory?

**Comment by bretrzaun** [comment]
Creating the phar in a shared folder of a Vagrant box caused that problem. Once I changed "output" property to a location outside the shared folder the error went away.

**Comment by kherge** [comment]
I'll close this since it appears to be an issue with your setup in Vagrant.
